language: swift
podfile: Example/Podfile

matrix:
  include:
    - osx_image: xcode10.2
      xcode_sdk: iphonesimulator12.2
      DESTINATION: "platform=iOS Simulator,name=iPhone 7"
    
    - osx_image: xcode11
      xcode_sdk: iphonesimulator13.0
      DESTINATION: "platform=iOS Simulator,name=iPhone 11"

before_install:
  - rvm use system
  - brew install ruby
  - sudo gem install cocoapods -v '1.8.0'
  - pod repo update

script:
  - xcodebuild clean build test -workspace Example/DKImagePickerControllerDemo.xcworkspace -scheme DKImagePickerControllerDemo -destination "$DESTINATION"
